version: '3.7'

services:
  chrome:
    image: justinribeiro/chrome-headless
    security_opt:
      - seccomp:"./chrome.json"
    command:
      - --disable-background-networking
      - --safebrowsing-disable-auto-update
      - --disable-sync
      - --metrics-recording-only
      - --disable-default-apps
      - --mute-audio
      - --no-first-run
      - --disable-background-timer-throttling
      - --disable-client-side-phishing-detection
      - --disable-popup-blocking
      - --disable-prompt-on-repost
      - --enable-automation
      - --password-store=basic
      - --use-mock-keychain
      - --disable-component-update
      - --autoplay-policy=no-user-gesture-required
      - --disable-notifications
      - --disable-hang-monitor
      - --disable-gpu
      - --headless
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
    networks:
      privacyscanner:
        ipv4_address: 172.28.0.2

networks:
  privacyscanner:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
